#!/bin/bash
#
# ddump 0.01
#
# Dumps the contents of a file to stdout which is then piped to less.
#
# Copyright (C) 2018 Trasicio Maina <cisiomaina@gmail.com>
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA.

version()
{
    env printf "ddump 0.01
    Copyright (C) 2018 Trasicio Maina <cisiomaina@gmail.com>
    This program is free software; you can redistribute it and/or modify it under the terms of the
    GNU General Public License version 3 as published by the Free Software Foundation.
    ""\n"
}

usage()
{
    env printf "\t ddump:\tddump [option] FILE \n\t Dump the contents of a file to stdout \n\n
    \t\tOptions:\n\t\t-h, --help\t\t Print this help message and exit \n\t\t-v, --version\t\t Print ddump version and exit\n\n\t\tYou may exit ddump by pressing \"q\" (Most commands that apply to LESS(1) may be used with ddump)\n\n"
}

while [ "$#" -gt 0 ]
    do
    case "$1" in
            --help)
            usage
            exit 0
            ;;
            -h)
            usage
            exit 0
            ;;
            -v)
            version
            exit 0
            ;;
            --version)
            version
            exit 0
            ;;
            --)
            shift || { usage; exit 1; }
            if [ -z "$FILE"]
            then
            FILE="$1"
                 fi
                 shift
                 [ "$#" -gt 0 ] && { usage; exit 1; }
                 ;;
            *)
            if [ -z "$FILE" ]
                then
                FILE="$1"
                     fi
                     shift
                     ;;
                esac
                done
                [ "$#" -gt 0 ] && { usage; exit 1; }
                [ -n "$FILE" ] || { usage; exit 1; }

# TODO (<cisiomaina@gmail.com>#1#10/09/18): Stop using less; get ddump to read the raw file data instead.

                cat "$FILE" | less || \
            { echo >&2 "Exited with a non-zero exit status"; exit 1; }

